# Generated by Django 5.1.2 on 2024-10-27 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Generic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Manufacturers/Brands',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generic_unit', models.CharField(help_text='Amount of generic such as 600gm, 700gm', max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('no_of_tablets', models.IntegerField(help_text='Number of tablets in a strip')),
                ('price', models.IntegerField()),
                ('batch_number', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('generic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.generic')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.manufacturer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
